name: flutter_3d_object
description: This is a flutter 3d object maker library.
version: 0.0.1
repository: https://github.com/Mohiuddin655-DEV/flutter_3d_object.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: